server:
  port: 8101

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: eureka_server_two